//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimientos()
        {
            this.Mantenimiento_Repuesto = new HashSet<Mantenimiento_Repuesto>();
        }
    
        public int ID_Mantenimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> ID_Mecanico { get; set; }
        public Nullable<int> ID_Vehiculo { get; set; }
        public Nullable<int> ID_Servicio { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento_Repuesto> Mantenimiento_Repuesto { get; set; }
        public virtual Mecanicos Mecanicos { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
