//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento_Repuesto
    {
        public int ID_Mantenimiento { get; set; }
        public int ID_Repuesto { get; set; }
        public Nullable<int> Cantidad_Usada { get; set; }
    
        public virtual Mantenimientos Mantenimientos { get; set; }
        public virtual Repuestos Repuestos { get; set; }
    }
}
